{"name": "test_case1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n +  where 2 = add(1, 1)", "trace": "def test_case1():\n>       assert 1 == add(1,1)\nE       assert 1 == 2\nE        +  where 2 = add(1, 1)\n\ntest_use_allure.py:13: AssertionError"}, "start": 1690273914425, "stop": 1690273914425, "uuid": "efe107c7-022d-4cba-9215-2d4f9da56519", "historyId": "d52f3de2ff5f68eb754f2e2e801dc5c8", "testCaseId": "5ff13808231db625c858688b0604d580", "fullName": "test_use_allure#test_case1", "labels": [{"name": "suite", "value": "test_use_allure"}, {"name": "host", "value": "DESKTOP-BVMI6KU"}, {"name": "thread", "value": "11496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_use_allure"}]}